### ISSUE TITLE
generate a lang file

### ISSUE THREAD

**Issue by ASchmidt84** [osinka/scala-i18n#7]
Is it possible to add the feature to generate a complete lang file with all keys which was not found in translation. So it is possible to test the gui and each function and to translate all not founded keys later.
Thank you
André

**Comment by alaz** [comment]
Hello,

Does Play Framework has such a feature?

Best,
Alexander

**Comment by ASchmidt84** [comment]
I dont think so.

**Comment by alaz** [comment]
Play Framework is supported by many developers and by company "Lightbend" with investments. This small library "scala-i18n" is built by the only developer who is [the only contributor](https://github.com/osinka/scala-i18n/graphs/contributors) so far. I am really sorry, but I have no bandwidth for this feature. I shall be happy to provide support and merge PR if you'd like to contribute.

**Comment by ASchmidt84** [comment]
I will help you and build this feature in the next time :)

**Comment by alaz** [comment]
Great. Looking forward!
(re-opening the issue)
