### ISSUE TITLE
Can .properties files be supported?

### ISSUE THREAD

**Issue by Catharz** [osinka/scala-i18n#8]
We're using Smartling as a translation service and the messages.txt file format for this is not supported. They do however support standard Java .properties files.

**Comment by alaz** [comment]
Why would you need an extra library for Java "properties" files? Do you feel Java's [ResourceBundle](https://docs.oracle.com/javase/8/docs/api/java/util/ResourceBundle.html) API is insufficient?

**Comment by Catharz** [comment]
Thanks @alaz, Java (or even Scala) isn't really my forte.
Our code just uses `messages.txt`, as per the readme.
That does look like it's what we need.
